package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
	"github.com/rscheurman/ToDoApp/to_do_app/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (ToDo)
// DB Table: Plural (to_dos)
// Resource: Plural (ToDos)
// Path: Plural (/to_dos)
// View Template Folder: Plural (/templates/to_dos/)

// ToDosResource is the resource for the ToDo model
type ToDosResource struct {
	buffalo.Resource
}

// List gets all ToDos. This function is mapped to the path
// GET /to_dos
func (v ToDosResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	toDos := &models.ToDos{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all ToDos from the DB
	if err := q.All(toDos); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, toDos))
}

// Show gets the data for one ToDo. This function is mapped to
// the path GET /to_dos/{to_do_id}
func (v ToDosResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty ToDo
	toDo := &models.ToDo{}

	// To find the ToDo the parameter to_do_id is used.
	if err := tx.Find(toDo, c.Param("to_do_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, toDo))
}

// New renders the form for creating a new ToDo.
// This function is mapped to the path GET /to_dos/new
func (v ToDosResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.ToDo{}))
}

// Create adds a ToDo to the DB. This function is mapped to the
// path POST /to_dos
func (v ToDosResource) Create(c buffalo.Context) error {
	// Allocate an empty ToDo
	toDo := &models.ToDo{}

	// Bind toDo to the html form elements
	if err := c.Bind(toDo); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(toDo)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, toDo))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "ToDo was created successfully")

	// and redirect to the to_dos index page
	return c.Render(201, r.Auto(c, toDo))
}

// Edit renders a edit form for a ToDo. This function is
// mapped to the path GET /to_dos/{to_do_id}/edit
func (v ToDosResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty ToDo
	toDo := &models.ToDo{}

	if err := tx.Find(toDo, c.Param("to_do_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, toDo))
}

// Update changes a ToDo in the DB. This function is mapped to
// the path PUT /to_dos/{to_do_id}
func (v ToDosResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty ToDo
	toDo := &models.ToDo{}

	if err := tx.Find(toDo, c.Param("to_do_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind ToDo to the html form elements
	if err := c.Bind(toDo); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(toDo)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, toDo))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "ToDo was updated successfully")

	// and redirect to the to_dos index page
	return c.Render(200, r.Auto(c, toDo))
}

// Destroy deletes a ToDo from the DB. This function is mapped
// to the path DELETE /to_dos/{to_do_id}
func (v ToDosResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty ToDo
	toDo := &models.ToDo{}

	// To find the ToDo the parameter to_do_id is used.
	if err := tx.Find(toDo, c.Param("to_do_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(toDo); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "ToDo was destroyed successfully")

	// Redirect to the to_dos index page
	return c.Render(200, r.Auto(c, toDo))
}
